[package]
name = "compute"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
half = "2.4.1"
metal = "0.30.0"
objc = "0.2.7"
